name: Build MGL for iOS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build MGL
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install make
          wget https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_arm64
          mv ldid_macosx_arm64 ldid && chmod +x ldid && sudo mv ldid /usr/local/bin

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: gmake build

      - name: Upload MGL-Core
        uses: actions/upload-artifact@v4
        with:
          name: libmgl-core
          path: build/libmgl_core.dylib
